//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class engineerTo {
    
    private engineerToItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public engineerToItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class engineerToItem {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Entity {
    
    private string createdByField;
    
    private string createdTimeField;
    
    private string generatorIDField;
    
    private string ownerDesignNameField;
    
    private string adequatelyNormalizedField;
    
    private string expectedVolumesField;
    
    private string fwdEngineeringStrategyNameField;
    
    private string growthPercentField;
    
    private string growthTypeField;
    
    private string maxVolumesField;
    
    private string minVolumesField;
    
    private string normalFormField;
    
    private engineerToItem[][] engineerToField;
    
    private EntityAttributes[] attributesField;
    
    private EntityIdentifiers[] identifiersField;
    
    private string classField;
    
    private string directorySegmentNameField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdTime {
        get {
            return this.createdTimeField;
        }
        set {
            this.createdTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string generatorID {
        get {
            return this.generatorIDField;
        }
        set {
            this.generatorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ownerDesignName {
        get {
            return this.ownerDesignNameField;
        }
        set {
            this.ownerDesignNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adequatelyNormalized {
        get {
            return this.adequatelyNormalizedField;
        }
        set {
            this.adequatelyNormalizedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string expectedVolumes {
        get {
            return this.expectedVolumesField;
        }
        set {
            this.expectedVolumesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fwdEngineeringStrategyName {
        get {
            return this.fwdEngineeringStrategyNameField;
        }
        set {
            this.fwdEngineeringStrategyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string growthPercent {
        get {
            return this.growthPercentField;
        }
        set {
            this.growthPercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string growthType {
        get {
            return this.growthTypeField;
        }
        set {
            this.growthTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maxVolumes {
        get {
            return this.maxVolumesField;
        }
        set {
            this.maxVolumesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string minVolumes {
        get {
            return this.minVolumesField;
        }
        set {
            this.minVolumesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string normalForm {
        get {
            return this.normalFormField;
        }
        set {
            this.normalFormField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(engineerToItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public engineerToItem[][] engineerTo {
        get {
            return this.engineerToField;
        }
        set {
            this.engineerToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntityAttributes[] attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identifiers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntityIdentifiers[] identifiers {
        get {
            return this.identifiersField;
        }
        set {
            this.identifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directorySegmentName {
        get {
            return this.directorySegmentNameField;
        }
        set {
            this.directorySegmentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityAttributes {
    
    private EntityAttributesAttribute[] attributeField;
    
    private string itemClassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntityAttributesAttribute[] Attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemClass {
        get {
            return this.itemClassField;
        }
        set {
            this.itemClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityAttributesAttribute {
    
    private string createdByField;
    
    private string createdTimeField;
    
    private string generatorIDField;
    
    private string ownerDesignNameField;
    
    private string nullsAllowedField;
    
    private string referedAttributeField;
    
    private string useField;
    
    private string logicalDatatypeField;
    
    private string domainField;
    
    private engineerToItem[][] engineerToField;
    
    private string nameField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdTime {
        get {
            return this.createdTimeField;
        }
        set {
            this.createdTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string generatorID {
        get {
            return this.generatorIDField;
        }
        set {
            this.generatorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ownerDesignName {
        get {
            return this.ownerDesignNameField;
        }
        set {
            this.ownerDesignNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nullsAllowed {
        get {
            return this.nullsAllowedField;
        }
        set {
            this.nullsAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referedAttribute {
        get {
            return this.referedAttributeField;
        }
        set {
            this.referedAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string use {
        get {
            return this.useField;
        }
        set {
            this.useField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string logicalDatatype {
        get {
            return this.logicalDatatypeField;
        }
        set {
            this.logicalDatatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(engineerToItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public engineerToItem[][] engineerTo {
        get {
            return this.engineerToField;
        }
        set {
            this.engineerToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityIdentifiers {
    
    private EntityIdentifiersIdentifier[] identifierField;
    
    private string itemClassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntityIdentifiersIdentifier[] identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string itemClass {
        get {
            return this.itemClassField;
        }
        set {
            this.itemClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityIdentifiersIdentifier {
    
    private string createdByField;
    
    private string createdTimeField;
    
    private string generatorIDField;
    
    private string ownerDesignNameField;
    
    private string pkField;
    
    private engineerToItem[][] engineerToField;
    
    private EntityIdentifiersIdentifierUsedAttributes[] usedAttributesField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string createdTime {
        get {
            return this.createdTimeField;
        }
        set {
            this.createdTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string generatorID {
        get {
            return this.generatorIDField;
        }
        set {
            this.generatorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ownerDesignName {
        get {
            return this.ownerDesignNameField;
        }
        set {
            this.ownerDesignNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pk {
        get {
            return this.pkField;
        }
        set {
            this.pkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(engineerToItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public engineerToItem[][] engineerTo {
        get {
            return this.engineerToField;
        }
        set {
            this.engineerToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("usedAttributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntityIdentifiersIdentifierUsedAttributes[] usedAttributes {
        get {
            return this.usedAttributesField;
        }
        set {
            this.usedAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityIdentifiersIdentifierUsedAttributes {
    
    private string attributeRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string attributeRef {
        get {
            return this.attributeRefField;
        }
        set {
            this.attributeRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entity", typeof(Entity))]
    [System.Xml.Serialization.XmlElementAttribute("engineerTo", typeof(engineerTo))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
